import sys

print("let")
print("pkgs = import <nixpkgs> {};")
print("p = pkgs.hello;")
print("drv = pkgs.stdenv.mkDerivation {")
print("name = \"hey\";")
a = ' '.join(sys.argv[1:])
print(f"buildInputs = with pkgs; [ {a} coreutils ];")
print("unpackPhase = \"true\";")
print("buildPhase = ''")
print("echo '#!/bin/bash' >> gather")
print("echo 'if [ $1 = '--app-the-gathering-softlink' ]; then' >> gather")
for ex in sys.argv[1:]:
    print(f"echo '${{pkgs.coreutils}}/bin/ln -s $ARGV0 {ex}' >> gather")
print("echo 'exit' >> gather")
print("echo 'fi' >> gather")
print("echo 'x=$(${pkgs.coreutils}/bin/basename \"$ARGV0\")' >> gather")
for ex in sys.argv[1:]:
    print(f"echo 'if [ $x = {ex} ]; then' >> gather")
    print(f"echo '${{pkgs.{ex}}}/bin/{ex} $@' >> gather")
    print("echo 'fi' >> gather")
print("chmod u+x gather")
print("'';")
print("installPhase = ''")
print("mkdir -p $out/bin")
print("cp gather $out/bin")
print("'';")
print("};")
print("in {")
print("type = \"app\";")
print("program = \"${drv}/bin/gather\";")
print("}")
